name: Build Millennium

on:
    workflow_dispatch:
        inputs:
            release_artifacts:
                description: 'Release build?'
                required: true
                default: 'no'

concurrency:
    group: ci-build
    cancel-in-progress: true

jobs:
    build-linux:
        permissions:
            contents: write
            issues: write
            pull-requests: write

        runs-on: ubuntu-latest

        steps:
            - name: ⚙️ Checkout repository
              uses: actions/checkout@v4
              with:
                  submodules: true

            - name: ⚙️ Download Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 20

            - name: ⚙️ Download Semantic Release
              run: |
                  npm install -g pnpm
                  pnpm install --save-dev semantic-release @semantic-release/github @semantic-release/exec @semantic-release/changelog @semantic-release/git
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: ⚙️ Get Next Version
              run: bash scripts/ci/posix/version.sh
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: ⚙️ Install GCC Dependencies
              run: |
                  sudo dpkg --add-architecture i386
                  sudo apt-get update
                  sudo apt-get install -y build-essential gcc-multilib g++-multilib

            - name: ⚙️ Download Python Dependencies
              run: |
                  wget https://github.com/shdwmtr/pybuilder/releases/download/v1.0.6/python-3.11.8-32-bit.tar.gz -O python-3.11.8-32-bit.tar.gz
                  mkdir -p ~/build/opt/python-i686-3.11.8
                  mkdir -p ~/build/usr/lib/millennium
                  mkdir -p /opt/python-i686-3.11.8/lib

                  tar -xzf python-3.11.8-32-bit.tar.gz -C ~/build/opt/python-i686-3.11.8
                  mv ~/build/opt/python-i686-3.11.8/python-build/* ~/build/opt/python-i686-3.11.8/

                  cp ~/build/opt/python-i686-3.11.8/lib/libpython-3.11.8.so /opt/python-i686-3.11.8/lib/libpython-3.11.8.so
                  ~/build/opt/python-i686-3.11.8/bin/python3.11 --version

            - name: ⚙️ Install CMake
              uses: jwlawson/actions-setup-cmake@v2
              with:
                  cmake-version: '3.21.1'

            - name: ⚙️ Install VCPKG
              run: sudo apt install libgtk-3-dev ninja-build && ./vendor/vcpkg/bootstrap-vcpkg.sh && ./vendor/vcpkg/vcpkg integrate install

            - name: 🛠️ Build Millennium Frontend
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  cd sdk && pnpm install && pnpm run build && cd ..
                  cd assets && pnpm install && npm run build && cd ..
                  bash scripts/ci/posix/mk-assets.sh

                  mkdir -p ~/build/usr/share/millennium/shims
                  cp -r ./sdk/typescript-packages/loader/build/* ~/build/usr/share/millennium/shims/

            - name: 🛠️ Build Millennium Backend
              run: |
                  cmake --preset=linux-release -G "Ninja" -DGITHUB_ACTION_BUILD=ON
                  # Build the project
                  cmake --build build --config Release -- -j$(nproc)

                  # Create final directory structure
                  mkdir -p ~/build/usr/lib/millennium
                  mkdir -p ~/build/usr/bin
                  mkdir -p ~/build/usr/share/millennium
                  mkdir -p ~/build/opt

                  # Copy binaries and libraries directly to final locations
                  cp ./build/libmillennium_x86.so ~/build/usr/lib/millennium/libmillennium_x86.so
                  cp ./build/unix-hooks/libmillennium_bootstrap_86x.so ~/build/usr/lib/millennium/libmillennium_bootstrap_86x.so
                  cp ./build/cli/millennium ~/build/usr/bin/millennium
                  chmod +x ~/build/usr/bin/millennium

                  # Copy additional assets
                  cp -r ~/env/ext/data/assets ~/build/usr/share/millennium/assets

            - name: 📤 Upload Build Artifact
              uses: actions/upload-artifact@v4
              with:
                  include-hidden-files: true
                  name: millennium-linux
                  path: ~/build/

    release:
        needs: [build-linux]
        runs-on: ubuntu-latest
        if: ${{ inputs.release_artifacts == 'yes' }}
        steps:
            - name: ⚙️ Checkout repository
              uses: actions/checkout@v4
              with:
                  submodules: true

            - name: ⚙️ Download Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 20

            - name: ⚙️ Install Semantic Release
              run: npm install --save-dev semantic-release @semantic-release/github @semantic-release/exec @semantic-release/changelog @semantic-release/git
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: ⚙️ Download Linux Build
              uses: actions/download-artifact@v4
              with:
                  name: millennium-linux
                  path: ./artifacts/linux

            - name: ⚙️ Bump Millennium Version
              id: read_version
              run: bash scripts/ci/posix/bump.sh
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: 🛠️ Release Millennium
              run: |
                  mkdir -p ./artifacts/release
                  cd ./artifacts/windows && zip -r ../release/millennium-v${{ steps.read_version.outputs.version }}-windows-x86_64.zip . && cd ../..
                  tar -czvf ./artifacts/release/millennium-v${{ steps.read_version.outputs.version }}-linux-x86_64.tar.gz -C ./artifacts/linux .
                  npx semantic-release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
